apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calendar-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Loli2601/weekly_calendar_app.git'
    targetRevision: HEAD
    path: chart/calendar-app  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
