apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ .Values.app }}
